добавила html, css
Asstafeva/admin-panel pull request #1
Opened 2021-09-19 20:42 UTC by Asstafeva

2021-09-20 12:50 UTC, Muslik commented on style.css
> +    padding: 2rem 3rem 0 3rem;
Можно сократить: ```padding: 2rem 3rem 0```

2021-09-20 12:51 UTC, Muslik commented on index.html
> +        <div class="table__wrapper">
А для чего тут wrapper? Можно стили сразу table задать

2021-09-20 13:23 UTC, Asstafeva commented on style.css
> +    padding: 2rem 3rem 0 3rem;
спасибо, исправлю.

2021-09-25 14:01 UTC, Muslik approved these changes
Опечатка в названии цвета

2021-09-25 14:01 UTC, Muslik commented on style.css
> +    background: var(--light-purpul);
purpul -> purple

2021-09-25 16:44 UTC, baryshkov requested changes
![Screenshot 2021-09-25 at 19 29 36](https://user-images.githubusercontent.com/35310783/134779488-5105662a-a7e0-4813-8023-cd087c6565e1.png)

2021-09-25 16:44 UTC, baryshkov commented on index.html
> +	<link rel="stylesheet" href="media.css">
что это за файл?

2021-09-25 16:44 UTC, baryshkov commented on index.html
> +<html lang="en">
разве язык страницы английский?

2021-09-25 16:44 UTC, baryshkov commented on style.css
> +}
зачем эти тени и дублирующийся паддинг?
![Screenshot 2021-09-25 at 19 29 26](https://user-images.githubusercontent.com/35310783/134778807-d87a6983-f2db-484e-872c-70d2ed52b02d.png)

2021-09-25 16:44 UTC, baryshkov commented on index.html
> +    <link rel="stylesheet" href="reset.css">
пустой файл, ресет не сделан

2021-09-25 16:44 UTC, baryshkov commented on style.css
> +    box-sizing: border-box;
свойство box-sizing, должно быть применено в ресете ко всем классам и хтмл тегам.

2021-10-04 12:48 UTC, baryshkov requested changes
![Screenshot 2021-10-04 at 15 43 35](https://user-images.githubusercontent.com/35310783/135854054-9d860071-f92f-4884-b5cf-593d4d7bc411.png)

мобильная верстка не рабит, также небольшие замечания по коду.

2021-10-04 12:48 UTC, baryshkov commented on pages/style.css
> +}
дублирующийся падинг тут зачем?

2021-10-04 12:48 UTC, baryshkov commented on pages/style.css
> +    font-weight: bold;
шрифт не соответствует макету

2021-10-04 12:48 UTC, baryshkov commented on pages/style.css
> +    font-size: 26px;
Предпочтительно всегда и везде указывать font-size в rem. Так как у разных пользователей браузера может быть настроен разный размер шрифта по-умолчанию, который за счет rem будет пропорционально увеличиваться.

2021-10-06 18:48 UTC, Asstafeva commented on pages/style.css
> +}
Добрый вечер. Почему дублирующийся?

2021-10-06 19:39 UTC, Asstafeva commented on pages/style.css
> +}
Все ошибки исправила, кроме этой и не понимаю, почему шрифт не соответствует макету...

2021-11-04 12:29 UTC, baryshkov commented on pages/style.css
> +}
> Все ошибки исправила, кроме этой и не понимаю, почему шрифт не соответствует макету...

дублирующийся потому-что вы применяете и к боди, и к хтмл паддинг, и у вас их два, зачем?

2021-11-04 15:37 UTC, merged